### ISSUE TITLE
Build process

### ISSUE THREAD

**Issue by pluginalan** [alebianco/ANE-Google-Analytics#16] opened 2013-07-01 10:58 UTC
Hi, and thanks kindly for this project - it's the only GA solution for AIR, so far as I know, and it does the job very well!

I'm trying to build the development branch (need the new 'App' stuff), and after a fashion (the undisclosed requirement to include your abcore github project in the actionscript/ dir) I'm stuck with a build error on the ext_ios target: 

exec] xcodebuild: error: Unknown build action '(all'.
     [exec] Build settings from command line:
     [exec]     ARCHS = armv7
     [exec]     SDKROOT = iphoneos7.0

I reckon sdkroot is incorrect - I recently installed the iOS7 / relevant XCode build; is this now creating a conflict with ANE-Google-Analytics build script and my environment?  

the ext_ios target injects the parameter -sdk ${sdk}, but I don't see where ${sdk} is set from, unless this: <option>-framework SystemConfiguration</option> from platform-iphone.xml is causing it to use a value set automatically during the latest XCode beta install?

There's no precompiled ANE in the Git repo, so building would appear to be my only option to get involved with the new library - though I'd like full build capabilities if I can manage it!

**Comment by EljoB** [comment] 2013-09-20 09:39
I'm also having trouble with building the development branch, trying to run the build script on Mac OS X (10.7.5).
After thinking that it might somehow be an outdated environment I'm having, I redownloaded latest Adobe AIR SDK and Android SDK (including platform API 8, Android 2.2).

I'm pretty sure I correctly modified the paths, but when I run ant, I get the following final output (omitting the succesfully built abcore) and I have no idea how to fix this:

-build-setup:
[getbuildtools] Using latest Build Tools: 18.1.0
     [echo] Resolving Build Target for android...
[gettarget] Project Target:   Android 2.2
[gettarget] API level:        8
     [echo] ----------
     [echo] Creating output directories if needed...
    [mkdir] Created dir: /Users/Huckleberry/Desktop/ga2/ANE-Google-Analytics/source/android/bin/rsObj
    [mkdir] Created dir: /Users/Huckleberry/Desktop/ga2/ANE-Google-Analytics/source/android/bin/rsLibs
     [echo] ----------
     [echo] Resolving Dependencies for android...
[dependency] Library dependencies:
[dependency] No Libraries
[dependency] 
[dependency] ------------------
[dependency] API<=15: Adding annotations.jar to the classpath.
     [echo] ----------
     [echo] Building Libraries with '-compile'...
   [subant] No sub-builds to iterate on

-code-gen:
[mergemanifest] No changes in the AndroidManifest files.
     [echo] Handling aidl files...
     [aidl] No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
     [echo] ----------
     [echo] Handling Resources...
     [aapt] No changed resources. R.java and Manifest.java untouched.
     [echo] ----------
     [echo] Handling BuildConfig class...
[buildconfig] Generating BuildConfig class.

-pre-compile:

-compile:
    [javac] Compiling 34 source files to /Users/Huckleberry/Desktop/ga2/ANE-Google-Analytics/source/android/bin/classes
    [javac] /Users/Huckleberry/Desktop/ga2/ANE-Google-Analytics/source/android/src/eu/alebianco/air/extensions/analytics/functions/TrackData.java:307: package Transaction does not exist
    [javac]     private Transaction.Item getProductAt(long i, FREArray products) throws FREWrongThreadException, FREInvalidObjectException, FRETypeMismatchException, FREASErrorException, FRENoSuchNameException {
    [javac]                        ^
    [javac] /Users/Huckleberry/Desktop/ga2/ANE-Google-Analytics/source/android/src/eu/alebianco/air/extensions/analytics/functions/SetCustomDimension.java:60: cannot find symbol
    [javac] symbol  : method setCustomDimension(java.lang.Integer,java.lang.String)
    [javac] location: class com.google.analytics.tracking.android.Tracker
    [javac]         tracker.setCustomDimension(index, value);
    [javac]                ^
    [javac] /Users/Huckleberry/Desktop/ga2/ANE-Google-Analytics/source/android/src/eu/alebianco/air/extensions/analytics/functions/SetCustomMetric.java:60: cannot find symbol
    [javac] symbol  : method setCustomMetric(java.lang.Integer,long)
    [javac] location: class com.google.analytics.tracking.android.Tracker
    [javac]         tracker.setCustomMetric(index, (long) value);
    [javac]                ^
    [javac] /Users/Huckleberry/Desktop/ga2/ANE-Google-Analytics/source/android/src/eu/alebianco/air/extensions/analytics/functions/TrackData.java:65: cannot find symbol
    [javac] symbol  : variable WARN
    [javac] location: class eu.alebianco.air.extensions.utils.LogLevel
    [javac]                 FREUtils.logEvent(context, LogLevel.WARN, "Hit type not recognized: {0}", type);
    [javac]                                                    ^
    [javac] /Users/Huckleberry/Desktop/ga2/ANE-Google-Analytics/source/android/src/eu/alebianco/air/extensions/analytics/functions/TrackData.java:83: cannot find symbol
    [javac] symbol  : method sendView(java.lang.String)
    [javac] location: class com.google.analytics.tracking.android.Tracker
    [javac]         tracker.sendView(screen);
    [javac]                ^
    [javac] /Users/Huckleberry/Desktop/ga2/ANE-Google-Analytics/source/android/src/eu/alebianco/air/extensions/analytics/functions/TrackData.java:122: cannot find symbol
    [javac] symbol  : method constructEvent(java.lang.String,java.lang.String,java.lang.String,java.lang.Long)
    [javac] location: class com.google.analytics.tracking.android.Tracker
    [javac]         Map<String, String> hit = tracker.constructEvent(category, action, label, value);
    [javac]                                          ^
    [javac] /Users/Huckleberry/Desktop/ga2/ANE-Google-Analytics/source/android/src/eu/alebianco/air/extensions/analytics/functions/TrackData.java:123: cannot find symbol
    [javac] symbol  : variable ModelFields
    [javac] location: class eu.alebianco.air.extensions.analytics.functions.TrackData
    [javac]         tracker.send(ModelFields.EVENT, hit);
    [javac]                      ^
    [javac] /Users/Huckleberry/Desktop/ga2/ANE-Google-Analytics/source/android/src/eu/alebianco/air/extensions/analytics/functions/TrackData.java:151: cannot find symbol
    [javac] symbol  : method constructException(java.lang.String,java.lang.Boolean)
    [javac] location: class com.google.analytics.tracking.android.Tracker
    [javac]         Map<String, String> hit = tracker.constructException(description, fatal);
    [javac]                                          ^
    [javac] /Users/Huckleberry/Desktop/ga2/ANE-Google-Analytics/source/android/src/eu/alebianco/air/extensions/analytics/functions/TrackData.java:152: cannot find symbol
    [javac] symbol  : variable ModelFields
    [javac] location: class eu.alebianco.air.extensions.analytics.functions.TrackData
    [javac]         tracker.send(ModelFields.EXCEPTION, hit);
    [javac]                      ^
    [javac] /Users/Huckleberry/Desktop/ga2/ANE-Google-Analytics/source/android/src/eu/alebianco/air/extensions/analytics/functions/TrackData.java:192: cannot find symbol
    [javac] symbol  : method constructTiming(java.lang.String,java.lang.Long,java.lang.String,java.lang.String)
    [javac] location: class com.google.analytics.tracking.android.Tracker
    [javac]         Map<String, String> hit = tracker.constructTiming(category, interval, name, label);
    [javac]                                          ^
    [javac] /Users/Huckleberry/Desktop/ga2/ANE-Google-Analytics/source/android/src/eu/alebianco/air/extensions/analytics/functions/TrackData.java:193: cannot find symbol
    [javac] symbol  : variable ModelFields
    [javac] location: class eu.alebianco.air.extensions.analytics.functions.TrackData
    [javac]         tracker.send(ModelFields.TIMING, hit);
    [javac]                      ^
    [javac] /Users/Huckleberry/Desktop/ga2/ANE-Google-Analytics/source/android/src/eu/alebianco/air/extensions/analytics/functions/TrackData.java:223: cannot find symbol
    [javac] symbol  : method constructSocial(java.lang.String,java.lang.String,java.lang.String)
    [javac] location: class com.google.analytics.tracking.android.Tracker
    [javac]         Map<String, String> hit = tracker.constructSocial(network, action, content);
    [javac]                                          ^
    [javac] /Users/Huckleberry/Desktop/ga2/ANE-Google-Analytics/source/android/src/eu/alebianco/air/extensions/analytics/functions/TrackData.java:224: cannot find symbol
    [javac] symbol  : variable ModelFields
    [javac] location: class eu.alebianco.air.extensions.analytics.functions.TrackData
    [javac]         tracker.send(ModelFields.SOCIAL, hit);
    [javac]                      ^
    [javac] /Users/Huckleberry/Desktop/ga2/ANE-Google-Analytics/source/android/src/eu/alebianco/air/extensions/analytics/functions/TrackData.java:280: package Transaction does not exist
    [javac]         Transaction.Builder builder = new Transaction.Builder(id, (long) (cost \* 1000000));
    [javac]                    ^
    [javac] /Users/Huckleberry/Desktop/ga2/ANE-Google-Analytics/source/android/src/eu/alebianco/air/extensions/analytics/functions/TrackData.java:280: package Transaction does not exist
    [javac]         Transaction.Builder builder = new Transaction.Builder(id, (long) (cost \* 1000000));
    [javac]                                                      ^
    [javac] /Users/Huckleberry/Desktop/ga2/ANE-Google-Analytics/source/android/src/eu/alebianco/air/extensions/analytics/functions/TrackData.java:288: cannot find symbol
    [javac] symbol  : class Transaction
    [javac] location: class eu.alebianco.air.extensions.analytics.functions.TrackData
    [javac]         Transaction transaction = builder.build();
    [javac]         ^
    [javac] /Users/Huckleberry/Desktop/ga2/ANE-Google-Analytics/source/android/src/eu/alebianco/air/extensions/analytics/functions/TrackData.java:292: package Transaction does not exist
    [javac]                 Transaction.Item item = getProductAt(i, products);
    [javac]                            ^
    [javac] /Users/Huckleberry/Desktop/ga2/ANE-Google-Analytics/source/android/src/eu/alebianco/air/extensions/analytics/functions/TrackData.java:323: package Transaction.Item does not exist
    [javac]         Transaction.Item.Builder builder = new Transaction.Item.Builder(sku, name, (long) (price \* 1000000), quantity);
    [javac]                         ^
    [javac] /Users/Huckleberry/Desktop/ga2/ANE-Google-Analytics/source/android/src/eu/alebianco/air/extensions/analytics/functions/TrackData.java:323: package Transaction.Item does not exist
    [javac]         Transaction.Item.Builder builder = new Transaction.Item.Builder(sku, name, (long) (price \* 1000000), quantity);
    [javac]                                                                ^
    [javac] 19 errors

BUILD FAILED
/Users/Huckleberry/Desktop/ga2/ANE-Google-Analytics/build/build.xml:147: The following error occurred while executing this line:
/Applications/AndroidSDK/sdk/tools/ant/build.xml:720: The following error occurred while executing this line:
/Applications/AndroidSDK/sdk/tools/ant/build.xml:734: Compile failed; see the compiler error output for details.

**Comment by alebianco** [comment] 2013-09-20 11:30
@EljoB 
I think it's a different issue
looks like it doesn't find the analytics java library. can you verify to have _libGoogleAnalyticsServices.jar_ and _FlashRuntimeExtensions.jar_ in your _android/libs_ folder? to be precise the analytics library should be version 2.0.x in case you have to download it

**Comment by EljoB** [comment] 2013-09-20 13:20
Thanks for your swift reply. I know it's a different issue, but thought it'd be easier to have a single 'build process' topic. Sorry if that isn't the case.

I have both .jar files in that location and I can see that the build script is including them (or is trying to, at the very least). Because when I run ant in debug mode, the following output is right before the errors. Still don't have a clue how to fix this:

[javac] Compiling 34 source files to /Users/Huckleberry/Desktop/ga2/ANE-Google-Analytics/source/android/bin/classes
    [javac] Using modern compiler
    [javac] Compilation arguments:
    [javac] '-d'
    [javac] '/Users/Huckleberry/Desktop/ga2/ANE-Google-Analytics/source/android/bin/classes'
    [javac] '-classpath'
    [javac] '/Users/Huckleberry/Desktop/ga2/ANE-Google-Analytics/source/android/bin/classes:/Users/Huckleberry/Desktop/ga2/ANE-Google-Analytics/source/android/libs/FlashRuntimeExtensions.jar:/Applications/AndroidSDK/sdk/tools/support/annotations.jar:/Users/Huckleberry/Desktop/ga2/ANE-Google-Analytics/source/android/libs/libGoogleAnalyticsServices.jar'
    [javac] '-sourcepath'
    [javac] '/Users/Huckleberry/Desktop/ga2/ANE-Google-Analytics/source/android/src:/Users/Huckleberry/Desktop/ga2/ANE-Google-Analytics/source/android/gen'
    [javac] '-target'
    [javac] '1.5'
    [javac] '-bootclasspath'
    [javac] '/Applications/AndroidSDK/sdk/platforms/android-8/android.jar'
    [javac] '-encoding'
    [javac] 'UTF-8'
    [javac] '-g'
    [javac] '-source'
    [javac] '1.5'

**Comment by alebianco** [comment] 2013-09-20 13:27
i'm trying to reproduce the issue with no luck
could you send me a detailed report of the steps you followed to run the build? which branch you checked out, which files you added or modified, where you run the script from etc ...

**Comment by EljoB** [comment] 2013-09-20 14:05
I'm working on a Mac and I already have XCode and iOS 5.1 SDK installed, hence my following steps were:

1) Download latest Flex SDK
2) Download latest AIR SDK
3) Download Android SDK + API 8 SDK Platform
4) Created 'ga' working folder on desktop and changed to that path
5) git clone --recursive https://github.com/alebianco/ANE-Google-Analytics.git
6) git checkout --track origin/development
7) git pull
8) copy FlashRuntimeExtensions.h and FlashRuntimeExtensions.jar to correct lib folders
9) Rename user.properties.eg to user.properties and modified paths to reflect sdk locations
10) Rename user.properties.eg in Abcode submodule to user.properties and modified path
11) Increase value minSdkVersion and targetSdkVersion in source/android/AndroidManifest.xml to 8 in order to prevent a warning (I like my build output as clean as possible)
12) Go to /build folder and run ant

Notice error output as posted before (abcore is compiled succesfully, Android classes aren't and build stops).

**Comment by alebianco** [comment] 2013-09-20 15:10
ok, first thing, switch to the master branch, it has been merged recently and the current develop branch is instable
then try again and compare with my output (using the -debug flag) https://gist.github.com/alebianco/6638818
also try without changing the targetSdk and minSdk ... it shouldn't make a difference but let's play it safe ...

**Comment by EljoB** [comment] 2013-09-23 09:12
The master branch builds fine and results in a 'NativeGATracker-v2.0.4.ane' file. I was under the impression though, that I should use the development branch as that's the only one using the v3 protocol, but please correct me if I'm wrong.

**Comment by alebianco** [comment] 2013-09-23 09:29
yes the dev branch is using the v3 protocol, but the integration work started only last week and it's far from complete. It might work already, if we figure out the building issue, but I wouldn't suggest using it just yet.

The master branch is now using the v2 protocol which should still work fine with the app profile on google analytics. If it doesn't I blame Google ... but let me know and I'll try to speedup the work on the v3 so you can have a working version even if a bit unstable/untested.

**Comment by EljoB** [comment] 2013-09-24 08:54
I've implemented the ANE file from the master branch and ran some tests. Seems to work nicely at the moment, so you don't have to rush anything for me. All your effort is already greatly appreciated! I'll keep an eye on future development of this extension.

Thanks!

**Comment by alebianco** [comment] 2013-09-24 08:57
awesome, i'll close the issue for now ... i've got some juicy news about the build process in the upcoming version, more updates in the next weeks :)

**Closed as completed by alebianco** 2013-09-24 08:57 UTC
Labels: enhancement
